version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker.env

  api_robyn:
    container_name: api_robyn
    build:
      context: ./
      dockerfile: Dockerfile-robyn
    ports:
      - "8000:8000"
    env_file:
      - docker.env